# Generated by Django 4.1.5 on 2023-03-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=50)),
                ('profile_picture_url', models.TextField()),
                ('tweet', models.TextField()),
                ('created_at', models.CharField(max_length=30)),
                ('likes', models.IntegerField(default=0)),
                ('retweets', models.IntegerField(default=0)),
            ],
        ),
    ]
