from django.urls import path,include
from .views import (UserID,UserTweets,Index,DataPage,HashtagMain,
                    HashtagResult,KeywordMain,KeywordResult,TweetCountMain,
                    TweetCountResult,KeywordTrendMain,KeywordTrendResult,
                    DailyCountryTrendSearchView,DailyCountryTrendSearchResultView,
                    yearlyTopChartsView,yearlyTopChartsResultsView,
                    KeywordResearchView,KeywordResearchResultView)

urlpatterns = [
    path('user-id/', UserID.as_view()),
    path('user-tweets/', UserTweets.as_view()),
    # path('test/', Test, name= 'test'),
    path('', Index, name= 'index'),
    path('result/', DataPage, name= 'result'),
    path('hashtag/', HashtagMain, name= 'hashtag'),
    path('hashtag/result/', HashtagResult, name= 'hashtagResult'),
    path('keyword/', KeywordMain, name= 'keyword'),
    path('keyword/result/', KeywordResult, name= 'keywordResult'),
    path('tweetCount/', TweetCountMain, name= 'tweetCount'),
    path('tweetCount/result/', TweetCountResult, name= 'tweetCountResult'),
    path('KeywordTrend/', KeywordTrendMain, name= 'keywordTrend'),
    path('KeywordTrend/result/', KeywordTrendResult, name= 'keywordTrendResult'),
    path('KeywordTrend/result/', KeywordTrendResult, name= 'keywordTrendResult'),
    path('DailyTrendSearch/', DailyCountryTrendSearchView, name= 'DailyCountryTrendSearch'),
    path('DailyTrendSearch/result/', DailyCountryTrendSearchResultView, name= 'DailyCountryTrendSearchResult'),
    path('YearlyTopCharts/', yearlyTopChartsView, name= 'YearlyTopCharts'),
    path('YearlyTopCharts/result/', yearlyTopChartsResultsView, name= 'YearlyTopChartsResult'),
    path('KeywordResearch/', KeywordResearchView, name= 'KeywordResearch'),   
    path('KeywordResearch/result/', KeywordResearchResultView, name= 'KeywordResearchResult'),   
]