from django.urls import path,include
from .views import (UserID,UserTweets,Index,UsernameMain,UsernameResult,HashtagMain,
                    HashtagResult,KeywordMain,KeywordResult,TweetCountMain,
                    TweetCountResult,KeywordTrendMain,KeywordTrendResult,
                    DailyCountryTrendSearchView,DailyCountryTrendSearchResultView,
                    yearlyTopChartsView,yearlyTopChartsResultsView,
                    KeywordResearchView,KeywordResearchResultView,TweetSuggestionView, TweetSuggestionResultView, Login,
                    ResearchTool,TweetThreadSuggestionView, TweetThreadSuggestionResultView,
                    NewsView)
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', Index, name= 'index'),
    path('login/', Login, name= 'login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='api/login.html'), name='logout'),
    path('researchTool/', ResearchTool, name='researchTool'),
    path('news/', NewsView, name='news'),
    path('user-id/', UserID.as_view()),
    path('user-tweets/', UserTweets.as_view()),
    # path('test/', Test, name= 'test'),
    path('username/', UsernameMain, name= 'username'),
    path('username/result/', UsernameResult, name= 'usernameResult'),
    path('hashtag/', HashtagMain, name= 'hashtag'),
    path('hashtag/result/', HashtagResult, name= 'hashtagResult'),
    path('keyword/', KeywordMain, name= 'keyword'),
    path('keyword/result/', KeywordResult, name= 'keywordResult'),
    path('tweetCount/', TweetCountMain, name= 'tweetCount'),
    path('tweetCount/result/', TweetCountResult, name= 'tweetCountResult'),
    path('KeywordTrend/', KeywordTrendMain, name= 'keywordTrend'),
    path('KeywordTrend/result/', KeywordTrendResult, name= 'keywordTrendResult'),
    path('DailyTrendSearch/', DailyCountryTrendSearchView, name= 'DailyCountryTrendSearch'),
    path('DailyTrendSearch/result/', DailyCountryTrendSearchResultView, name= 'DailyCountryTrendSearchResult'),
    path('YearlyTopCharts/', yearlyTopChartsView, name= 'YearlyTopCharts'),
    path('YearlyTopCharts/result/', yearlyTopChartsResultsView, name= 'YearlyTopChartsResult'),
    path('KeywordResearch/', KeywordResearchView, name= 'KeywordResearch'),   
    path('KeywordResearch/result/', KeywordResearchResultView, name= 'KeywordResearchResult'),   
    path('aiSuggestion/', TweetSuggestionView, name= 'AISuggestion'),   
    path('aiSuggestion/result/', TweetSuggestionResultView, name= 'AISuggestionResult'),   
    path('aiThreadSuggestion/', TweetThreadSuggestionView, name= 'AIThreadSuggestion'),   
    path('aiThreadSuggestion/result/', TweetThreadSuggestionResultView, name= 'AIThreadSuggestionResult'),   
]